pull_request_rules:
  - name: template-probe-1
    conditions:
      - base=main
    actions:
      comment:
        message: |
          arith: {{ 7 * 7 }}
          concat: {{ "a" ~ "b" }}
          author: {{ author }}
          number: {{ number }}
